config/routes.rb
TestApp::Application.routes.draw do
  
  match '/create',  :to => 'items#new'

  match '/contact', :to => 'pages#contact'
  
  
  resources :items do
    collection do
      post :sort
    end
  end
  

  root :to => 'pages#home'

end

app/models/item.rb
class Item < ActiveRecord::Base
  #acts_as_list
  attr_accessible :title, :position

  validates :title, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def new
    @item = Item.new
    @title = "Create New Item"
  end
  
  def index
    @title = "All items"
    @items = Item.all
  end
  
  def show
    @item = Item.find(params[:id])
    @title = @item.title
  end
  
  def create
    @item = Item.new(params[:item])
    if @item.save
      flash[:success] = "New Item Created!"
      redirect_to @item
    else
      @title = "Create New Item"
      render 'new'
    end
  end
  
  def edit
    @item = Item.find(params[:id])
    @title = "Edit item"
  end
  
  def update
    @item = Item.find(params[:id])
    if @item.update_attributes(params[:item])
      flash[:success] = "Item updated."
      redirect_to @item
    else
      @title = "Edit item"
      render 'edit'
    end
  end
  
def sort
  params[:items].each_with_index do |id, index|  
    Item.update_all(['position=?', index+1], ['id=?', id])  
  end  
  render :nothing => true  
end 

def index  
  @items = Item.all(:order => 'position')  
end  

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end

  def contact
    @title = "Contact"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # Return a title on a per-page basis.
  def title
	base_title = "My Test Site"
	if @title.nil?
	  base_title
	else
	  "#{base_title} | #{@title}"
	end
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/items/edit.html.erb
<h1>Edit Item</h1>

<%= form_for(@item) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
	<%= f.label :title %><br />
	<%= f.text_field :title %>
  </div>
  <div class="field">
	<%= f.label :position %><br />
	<%= f.text_field :position %>
  <div class="actions">
	<%= f.submit "Update" %>
  </div>
<% end %>


app/views/items/index.html.erb
<h1>All items</h1>

<%= link_to "Create New Item", create_path %>

<ul id="items">
  <% @items.each do |item| %>


	<% content_tag_for :li, item do %> 
 	<span class="handle">[drag]</span>
	  <%= link_to item.title, item %> 

	<% end %>  

  <% end %>
</ul>
<%= sortable_element("items", :url => sort_items_path, :handle => "handle") %> 


app/views/items/new.html.erb
<h1>New Item</h1>

<%= form_for(@item) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
	<%= f.label :title %><br />
	<%= f.text_field :title %>
  </div>
  <div class="field">
	<%= f.label :position %><br />
	<%= f.text_field :position %>
  </div>
  <div class="actions">
	<%= f.submit "Create Item" %>
  </div>
<% end %>

app/views/items/show.html.erb
<table class="profile" summary="Profile information">
  <tr>
	<td class="main">
	  <h1>
		<%= @item.title %>
	  </h1>
	</td>
	<td class="sidebar round">
	  <strong>Title</strong> <%= @item.title %><br />
	  <strong>URL</strong>  <%= link_to item_path(@item), @item %>
	  <strong>Edit</strong> <li><%= link_to "Edit", edit_item_path(@item) %>
	</td>
  </tr>
</table>




app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
	<ul>
	  <li><%= link_to "About", '#' %></li>
	  <li><%= link_to "Contact", '#' %></li>
	  <li><a href="http://news.railstutorial.org/">News</a></li>
	  <li><a href="http://www.railstutorial.org/">Rails Tutorial</a></li>
	</ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>

  <%= image_tag("http://profile.ak.fbcdn.net/hprofile-ak-snc4/50254_340377697003_6059318_n.jpg", :alt => "Sample App", :class => "round") %>
  <nav class="round">
    <%= render 'shared/modules' %>
  </nav>
</header>

app/views/layouts/_modules.html.erb
	<ul>
	  <li><%= link_to "Home", root_path %></li>
	  <li><%= link_to "Items", items_path %></li>
	  <li><%= link_to "Blank Link", '#' %></li>
	</ul>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
      <%= javascript_include_tag :defaults %> 
    <%= render 'layouts/stylesheets' %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <section class="round">
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
      <%= debug(params) %>
    </div>
  </body>
</html>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>HOME</h1>
<p>Sup foo?</p>
	<%= render 'shared/modules' %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
	<h2><%= pluralize(object.errors.count, "error") %> 
		prohibited this <%= object.class.to_s.underscore.humanize.downcase %> 
		from being saved:</h2>
	<p>There were problems with the following fields:</p>
	<ul>
	<% object.errors.full_messages.each do |msg| %>
	  <li><%= msg %></li>
	<% end %>
	</ul>
  </div>
<% end %>

app/views/shared/_modules.html.erb
	<ul>
	  <li><%= link_to "Home", root_path %></li>
	  <li><%= link_to "Items", items_path %></li>
	  <li><%= link_to "Do Not Click This", '#' %></li>
	</ul>